// product list
export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
// product item
export const PRODUCT_ITEM_REQUEST = "PRODUCT_ITEM_REQUEST";
export const PRODUCT_ITEM_SUCCESS = "PRODUCT_ITEM_SUCCESS";
export const PRODUCT_ITEM_FAIL = "PRODUCT_ITEM_FAIL";
// cart
export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
